[FIX] Quiz Backstack
coding-blocks/CBOnlineApp pull request #639
Opened 2020-04-25 21:43 UTC by iamspathan

Fixes #632 
Changes:Replace FragmentPagerAdapter with FragmentStatePagerAdapter and ParentFragmentManager with ChildFragmentManager

2020-05-01 09:28 UTC, aggarwalpulkit596 requested changes

2020-05-01 09:28 UTC, aggarwalpulkit596 commented on app/src/main/java/com/codingblocks/cbonlineapp/mycourse/quiz/QuizResultFragment.kt
> +class QuizResultFragment(val quizAttemptId: String) : BaseCBFragment() {
use newInstance to pass quizId

2020-05-01 09:47 UTC, iamspathan commented on app/src/main/java/com/codingblocks/cbonlineapp/mycourse/quiz/QuizResultFragment.kt
> +class QuizResultFragment(val quizAttemptId: String) : BaseCBFragment() {
Okay

2020-05-04 11:35 UTC, aggarwalpulkit596 approved these changes

2020-05-06 22:11 UTC, merged