Added Empty View in Notes Tab
coding-blocks/CBOnlineApp pull request #671
Opened 2020-05-11 04:47 UTC by prathamk22

Fixes #662 
Changes: Added a Linearlayout which contains empty view of notes icon, title and sub text of it

Screenshots for the change:
![vlcsnap-2020-05-11-10h13m05s221](https://user-images.githubusercontent.com/32957484/81524883-7cf0d680-9370-11ea-963c-81f35fe8b3fa.png)

2020-05-11 08:14 UTC, aggarwalpulkit596 requested changes

2020-05-11 08:14 UTC, aggarwalpulkit596 commented on app/src/main/res/layout/fragment_notes.xml
> +            android:text="Click on + to add a new note."
Move all hardcoded strings to strings.xml

2020-05-11 08:14 UTC, aggarwalpulkit596 commented on app/src/main/java/com/codingblocks/cbonlineapp/mycourse/player/notes/VideoNotesFragment.kt
> +            playerNotesRv.visibility = View.VISIBLE
use isVisible = true or isVisible = false

2020-05-11 08:14 UTC, aggarwalpulkit596 commented on app/src/main/java/com/codingblocks/cbonlineapp/mycourse/player/notes/VideoNotesFragment.kt
> +            if (it.isNullOrEmpty()) {
can be simplified by
`showEnptyView(it.isNullOrEmpty())`

2020-05-11 10:33 UTC, prathamk22 commented
@aggarwalpulkit596 changes done as per feedback.

2020-05-15 11:35 UTC, aggarwalpulkit596 approved these changes

2020-05-15 11:36 UTC, merged