Tracks/shimmer
coding-blocks/CBOnlineApp pull request #673
Opened 2020-05-11 21:46 UTC by iamspathan

Fixes #649 

Changes: added shimmer in In All Learning Tracks and Learning Tracks Course

2020-05-13 12:20 UTC, aggarwalpulkit596 requested changes

2020-05-13 12:20 UTC, aggarwalpulkit596 commented on app/src/main/java/com/codingblocks/cbonlineapp/tracks/LearningTracksActivity.kt
> +        activity_learning_shimmer.showShimmer(true)
use camelcase

2020-05-13 12:20 UTC, aggarwalpulkit596 commented on app/src/main/res/layout/item_skeleton_track_course_card.xml
> +<androidx.cardview.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android"
use material card view

2020-05-13 18:41 UTC, iamspathan commented on app/src/main/res/layout/item_skeleton_track_course_card.xml
> +<androidx.cardview.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android"
Changes made in the last commit

2020-05-13 18:41 UTC, iamspathan commented on app/src/main/java/com/codingblocks/cbonlineapp/tracks/LearningTracksActivity.kt
> +        activity_learning_shimmer.showShimmer(true)
Changes made in the last commit

2020-05-15 11:33 UTC, aggarwalpulkit596 commented
@iamspathan always add a screenshot for UI related issues

2020-05-15 20:24 UTC, iamspathan commented
> @iamspathan always add a screenshot for UI related issues
Sure.  Screenshot added

2020-05-15 21:44 UTC, merged