Updated #716
coding-blocks/CBOnlineApp pull request #771
Opened 2020-05-16 17:00 UTC by adiig7

Fixes #716 

**Changes:**
1. Added an image(ic_content_copy) in drawable folder.
2. Updated the xml file to add that image beside the referral code.
3. Updated the Referral Activity by setting onClick for the image and initializing using *lazy*.

Screenshots for the change:
![Screenshot_20200516-110346_(Debug)Coding Blocks](https://user-images.githubusercontent.com/54351909/82125596-9c4e9000-97c4-11ea-95c1-8344c2431d14.jpg)

2020-05-16 17:23 UTC, aggarwalpulkit596 approved these changes

2020-05-16 23:48 UTC, aggarwalpulkit596 requested changes

2020-05-16 23:48 UTC, aggarwalpulkit596 commented on app/src/main/java/com/codingblocks/cbonlineapp/profile/ReferralActivity.kt
> +        copy_clipboard?.setOnClickListener(View.OnClickListener {
why nullable?

2020-05-16 23:48 UTC, aggarwalpulkit596 commented on app/src/main/java/com/codingblocks/cbonlineapp/profile/ReferralActivity.kt
> +            Toast.makeText(applicationContext, "Copied to Clipboard",
use toast() extension function

2020-05-17 16:27 UTC, merged

2020-05-17 23:51 UTC, iamspathan commented on app/src/main/java/com/codingblocks/cbonlineapp/profile/ReferralActivity.kt
>  import org.jetbrains.anko.share
@adiig7 You haven't imported Clipboard and toast, which was lead to a crash for others. Please review your code once before commit.