Fixes issue 718
coding-blocks/CBOnlineApp pull request #836
Opened 2020-05-25 06:50 UTC by AkshobhyaP

Fixes #718 

Hides FAB and shows a no content message when there is no content to display.

Screenshots for the change:
![20200525_110531](https://user-images.githubusercontent.com/18425237/82786288-f238cd00-9e81-11ea-89a2-28a6193b8dea.gif)

2020-05-25 06:54 UTC, AkshobhyaP commented
@aggarwalpulkit596 please review.

2020-05-25 16:47 UTC, aggarwalpulkit596 requested changes

2020-05-25 16:47 UTC, aggarwalpulkit596 commented on app/src/main/res/layout/fragment_course_content.xml
> +   <androidx.coordinatorlayout.widget.CoordinatorLayout
Why do you need a coordinator layout ?

2020-05-25 16:54 UTC, AkshobhyaP commented on app/src/main/res/layout/fragment_course_content.xml
> +   <androidx.coordinatorlayout.widget.CoordinatorLayout
To align the text view in the middle of the screen when the recycler view is gone so both the layouts overlap each other in the coordinator layout. In using any other layout when the recycler view was made invisible the text would jump to top as the main layout is linear.

2020-05-27 12:49 UTC, aggarwalpulkit596 requested changes

2020-05-27 12:49 UTC, aggarwalpulkit596 commented on app/src/main/res/layout/fragment_course_content.xml
> +   <androidx.coordinatorlayout.widget.CoordinatorLayout
use match parent as height and use gravity for text view I think that would do the job also try to align the theme of text with the app

2020-05-29 06:25 UTC, aggarwalpulkit596 commented
@AkshobhyaP any updates on this ?

2020-05-29 06:27 UTC, AkshobhyaP commented
@aggarwalpulkit596 yeah, I will add commits by today.

2020-06-01 06:46 UTC, aggarwalpulkit596 commented
@AkshobhyaP can you add a screenshot of updated UI

2020-06-01 06:47 UTC, aggarwalpulkit596 approved these changes

2020-06-02 13:16 UTC, AkshobhyaP commented
@aggarwalpulkit596 I've added the updated gif.

2020-06-04 06:31 UTC, merged