Used Space Progress issue fixed
coding-blocks/CBOnlineApp pull request #857
Opened 2020-06-05 12:51 UTC by hardik0899

Fixes #696 

Progress Bar was not showing the space used after downloading the videos from the courses. But now its fixed and I have tested it on 3 different devices. Its working awesome :)

Screenshots for the change:
![Screenshot_2020-06-05-18-14-09-25](https://user-images.githubusercontent.com/36165541/83878142-4f256480-a759-11ea-8034-5663c3cb3e1e.png)

2020-06-08 06:18 UTC, hardik0899 commented
@aggarwalpulkit596 Bhayia pls have a look whenever you are free.

2020-06-09 14:06 UTC, aggarwalpulkit596 requested changes

2020-06-09 14:06 UTC, aggarwalpulkit596 commented on app/src/main/java/com/codingblocks/cbonlineapp/settings/SettingsActivity.kt
> +        val usedSpace : Double = file?.let { folderSize(it) }!!.toDouble() / 1048576
Can you not use `!!` operator

2020-06-10 05:04 UTC, hardik0899 commented on app/src/main/java/com/codingblocks/cbonlineapp/settings/SettingsActivity.kt
> +        val usedSpace : Double = file?.let { folderSize(it) }!!.toDouble() / 1048576
Ok will do this

2020-06-14 05:59 UTC, hardik0899 commented
@aggarwalpulkit596 done the changes pls review once again the latest commit

2020-06-23 15:56 UTC, merged