Dark mode
coding-blocks/CBOnlineApp pull request #874
Opened 2020-06-16 09:16 UTC by prathamk22

Fixes #736
Changes: 
Changed all instances of black to head
Changed all instances of greyish to subHead
Made new night-color, night-style file for light and dark theme
Since it is a draft pull request, some changes are left.
Screenshots for the change:
https://youtu.be/fDXmWAcF2fM

2020-06-21 12:46 UTC, aggarwalpulkit596 requested changes

2020-06-21 12:46 UTC, aggarwalpulkit596 commented on app/src/main/res/values-night/styles.xml
> +<resources>
Why do we need a style file for dark mode?

2020-06-21 12:46 UTC, aggarwalpulkit596 commented on app/src/main/res/values-night/colors.xml
> +    <color name="pastel_red">#e74e4b</color>
and if colors are the same for both the mode then, in that case, they shouldn't be declared again and again

2020-06-23 18:37 UTC, prathamk22 commented
@aggarwalpulkit596

2020-06-25 16:28 UTC, prathamk22 commented
@aggarwalpulkit596

2020-07-29 16:16 UTC, prathamk22 commented
@aggarwalpulkit596 Bhaiye isse bhi review kardo.

2020-10-11 14:05 UTC, closed without merging